### ISSUE TITLE
Not building on Ubuntu 24.04

### ISSUE THREAD

**Issue by trilbytim** [tbsdtv/media_build#82]
I'm trying to build on a new installation of Ubuntu 24.04 (in order to run a Satellite  tuner card with MythTV, trying to set it up for my parents while I'm home for xmas!). I believe I have installed all the dependencies required and I have installed the kernel headers. Running the build script exits with the following error:
```
/home/rosebank/Driver/media_build/v4l/ccs-core.c: In function 'ccs_set_ctrl':
/home/rosebank/Driver/media_build/v4l/ccs-core.c:668:21: error: too many arguments to function 'pm_runtime_get_if_active'
  668 |         pm_status = pm_runtime_get_if_active(&client->dev, true);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/rosebank/Driver/media_build/v4l/ccs-core.c:22:
./include/linux/pm_runtime.h:75:12: note: declared here
   75 | extern int pm_runtime_get_if_active(struct device *dev);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~
make[4]: *** [scripts/Makefile.build:243: /home/rosebank/Driver/media_build/v4l/ccs-core.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [/usr/src/linux-headers-6.8.0-51-generic/Makefile:1925: /home/rosebank/Driver/media_build/v4l] Error 2
make[2]: *** [Makefile:240: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-6.8.0-51-generic'
make[1]: *** [Makefile:53: default] Error 2
make[1]: Leaving directory '/home/rosebank/Driver/media_build/v4l'
make: *** [Makefile:26: all] Error 2
build failed at ./build line 554
```
I've attached the complete Terminal output in the text file
Happy Christmas all!
[terminal output.txt](https://github.com/user-attachments/files/18246103/terminal.output.txt)

**Comment by crazycat69** [comment]
https://github.com/tbsdtv/linux_media/issues/370

Look like forced backport from newer kernels > 6.8
Disable v6.8-ccs.patch in [media_build/backports/backports.txt](https://github.com/tbsdtv/media_build/blob/latest/backports/backports.txt#L44)

**Comment by trilbytim** [comment]
Thank you! Yes, that's worked. Merry Christmas!
